name: pina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  http: ^1.6.0
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/instagram.png
